services:
  - type: web
    name: water-quality-monitoring
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_KEY
        value: Vasu@123
      - key: THINGSPEAK_CHANNEL_ID
        value: "2845308"
      - key: THINGSPEAK_READ_API_KEY
        value: "7K0QBM6EM1OV910C"
      - key: FLASK_ENV
        value: production
    plan: free 